#!/usr/bin/env python3
import os
import subprocess
import sys
import yaml
import json


upload_db = False
download_db = False
dev = False
port = None
user = None
file_path = "./ansible/inventory/hosts"

with open('.environmentals.json', 'r') as file:
    env_data = json.load(file)

with open('k8s-manifests/ngrok-ingress.yaml', 'r') as file:
    data = yaml.safe_load(file)

data['spec']['rules'][0]['host'] = env_data["NGROK_DOMAIN"]

with open('k8s-manifests/ngrok-ingress.yaml', 'w') as file:
    yaml.safe_dump(data, file)

if  "--help" in sys.argv or "-h" in sys.argv or len(sys.argv) < 2:
    print("Usage:\n \t python3 solveploy.py target_ip [options]"
          "\n\nOptions:\n"
          "\t--target-username: Username of the target machine. Default is 'ucloud'\n"
          "\t--upload-database: Upload the database from the a .sql file to the target machine. File must be named 'db.sql' and must be located in root folder of project. Default is False\n"
          "\t--download-database: Download the database from the target machine. Downloaded file is located in root folder of project named 'downloaded_db.sql'\n"
          "\t--dev: Deploys the project locally in development mode in Minikube.\n"
          "\t-v: Verbose mode. Prints the command that is being executed.\n")
    exit()

if "--upload-database" in sys.argv:
    upload_db = True

if "--download-database" in sys.argv:
    download_db = True

if "--target-username" in sys.argv:
    user = sys.argv[sys.argv.index("--target-username") + 1]
else:
    user = "ucloud"

if "--dev" in sys.argv:
    command = "ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook ansible/playbooks/dep_dev.yml -i ansible/inventory/localhosts -K"
    if "-v" in sys.argv:
        print("EXECUTING COMMAND: ", command)
    subprocess.run(command, shell=True)
    exit()



host = sys.argv[1] 

content = f'''[kubernetes_hosts]
target_vm ansible_host={host} ansible_user={user}
'''

with open(file_path, "w") as file:
    file.write(content)
    file.close()

if not download_db:
    command = "ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook ansible/playbooks/dep_prod.yml -i ansible/inventory/hosts"
    if "-v" in sys.argv:
        print("EXECUTING COMMAND: ", command)
    subprocess.run(command, shell=True)
    if upload_db:
        command = "ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook ansible/playbooks/upload_db.yml -i ansible/inventory/hosts"
        if "-v" in sys.argv:
            print("EXECUTING COMMAND: ", command)
        subprocess.run(command, shell=True)

if download_db:
    command = "ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook ansible/playbooks/download_db.yml -i ansible/inventory/hosts"
    subprocess.run(command, shell=True)