'''
This module is automatically generated by make_pfolio.py. Don't modify it!
'''

DEF_PFOLIO = {'gecode': {'solver': 'gecode', 'name': 'Gecode', 'conv_opts': '', 'solv_opts': '', 'constraint': 'constraint int_lin_le([1,-1],[LHS,RHS],-1)'}, 'highs': {'solver': 'highs', 'name': 'HiGHS', 'conv_opts': '-O3', 'solv_opts': '', 'constraint': 'constraint int_lin_le([1,-1],[LHS,RHS],-1)'}, 'chuffed': {'solver': 'chuffed', 'name': 'Chuffed', 'conv_opts': '', 'solv_opts': '', 'constraint': 'constraint int_lin_le([1,-1],[LHS,RHS],-1)'}}

