apiVersion: apps/v1
kind: Deployment
metadata:
  name: solver-handler
spec:
  selector:
    matchLabels:
      app: solver-handler
  template:
    metadata:
      labels:
        app: solver-handler
    spec:
      restartPolicy: Always
      containers:
        - name: solver-handler
          image: solver-handler:latest
          imagePullPolicy: Never
          env:
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: message-broker-default-user
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: message-broker-default-user
                  key: password
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          ports:
            - containerPort: 5001
