---
- name: Install Ansible Galaxy roles
  become: true
  hosts: kubernetes_hosts
  connection: local
  vars:
    kubeconfig_path: "/home/hmbl/.kube/config"
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"

  tasks:
    - name: Add user to docker group
      become: yes
      user:
        name: "hmbl"
        groups: docker
        append: yes
      tags: 
        - docker
      
    - name: Set Docker socket permissions
      become: yes
      file:
        path: /var/run/docker.sock
        mode: "0777"
      tags:
        - docker

    - name: Start minikube
      become: false
      command: minikube start --cpus=4 --memory=5000 --driver=docker

    - name: install pip3
      ansible.builtin.package:
        name: python3-pip
        state: present
  
    - name: install python3 libraries
      ansible.builtin.pip:
        name: "{{ item }}"
      loop:
        - kubernetes
        - openshift
        - docker
        - PyYAML
    
    - name: Create namespaces
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../../k8s-manifests/namespace-creation.yaml') | from_yaml_all }}"
    
    - name: Add Bitnami Helm repository
      ansible.builtin.command: helm repo add bitnami https://charts.bitnami.com/bitnami

    - name: Update Helm repositories
      ansible.builtin.command: helm repo update

    - name: Deploy RabbitMQ
      kubernetes.core.helm:
        name: rabbitmq
        chart_ref: bitnami/rabbitmq
        release_namespace: rabbitmq-system
        values:
          existingSecret: rabbitmq-credentials
          replicaCount: 3
          persistence:
            enabled: true
          rabbitmq:
            rabbitmq.conf: |
              heartbeat_timeout = 3600
    
    - name: Get secret from rabbitmq-system namespace
      kubernetes.core.k8s_info:
        kind: Secret
        name: rabbitmq
        namespace: rabbitmq-system
      register: secret_info
      until: (secret_info.resources | default([])) | length > 0
      retries: 20
      delay: 10

    - name: Create secret in default namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: "rabbitmq"
            namespace: default
          type: "{{ secret_info.resources[0].type }}"
          data: "{{ secret_info.resources[0].data }}"

    - name: Apply Kubernetes deployments and services
      kubernetes.core.k8s:
        definition: "{{ item }}"
      loop:
        - "{{ lookup('file', '../../k8s-manifests/postgres-pv.yaml') | from_yaml_all }}"
        - "{{ lookup('file', '../../k8s-manifests/postgres-pvc.yaml') | from_yaml_all }}"
        - "{{ lookup('file', '../../k8s-manifests/cluster-role-job-creator.yaml') | from_yaml_all }}"
        - "{{ lookup('file', '../../k8s-manifests/clusterrolebinding-job-creator.yaml') | from_yaml_all }}"
        - "{{ lookup('file', '../../k8s-manifests/api-gateway-deployment.yaml') | from_yaml_all }}"
        - "{{ lookup('file', '../../k8s-manifests/api-gateway-service.yaml') | from_yaml_all }}"
        - "{{ lookup('file', '../../k8s-manifests/job-handler-deployment.yaml') | from_yaml_all }}"
        - "{{ lookup('file', '../../k8s-manifests/job-handler-service.yaml') | from_yaml_all }}"
        - "{{ lookup('file', '../../k8s-manifests/knowledge-base-database-deployment.yaml') | from_yaml_all }}"
        - "{{ lookup('file', '../../k8s-manifests/knowledge-base-database-service.yaml') | from_yaml_all }}"
        - "{{ lookup('file', '../../k8s-manifests/knowledge-base-deployment.yaml') | from_yaml_all }}"
        - "{{ lookup('file', '../../k8s-manifests/knowledge-base-service.yaml') | from_yaml_all }}"
        - "{{ lookup('file', '../../k8s-manifests/frontend-deployment.yaml') | from_yaml_all }}"
        - "{{ lookup('file', '../../k8s-manifests/frontend-service.yaml') | from_yaml_all }}"
    
