---
- hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Build base Docker image
      community.docker.docker_image_build:
        path: ../../base-image
        name: solveploy-backend-base-image
        tag: latest
    
    - name: Build frontend Docker image
      community.docker.docker_image_build:
        path: ../../service/frontend
        name: frontend
        tag: latest
    
    - name: Build api-gateway Docker image
      community.docker.docker_image_build:
        path: ../../service/api-gateway
        name: api-gateway
        tag: latest
    
    - name: Build job-handler Docker image
      community.docker.docker_image_build:
        path: ../../service/job-handler
        name: job-handler
        tag: latest
    
    - name: Build knowledge-bank Docker image
      community.docker.docker_image_build:
        path: ../../service/knowledge-bank
        name: knowledge-bank
        tag: latest

    - name: Build mzn-pod Docker image
      community.docker.docker_image_build:
        path: ../../service/mzn-pod
        name: mzn-pod
        tag: latest
    
    - name: Build sat-pod Docker image
      community.docker.docker_image_build:
        path: ../../service/sat-pod
        name: sat-pod
        tag: latest

    - name: Build maxsat-pod Docker image
      community.docker.docker_image_build:
        path: ../../service/maxsat-pod
        name: maxsat-pod
        tag: latest


   # - name: Deploy Kubernetes files
    #  community.kubernetes.k8s:
     #   state: present
      #  src: /path/to/kubernetes/file