---
- name: Install Ansible Galaxy roles
  hosts: localhost
  connection: local
  become: true
  roles:
    - geerlingguy.docker
    - geerlingguy.helm
    - gantsign.minikube
    - robertdebock.kubectl