---
- name: Install Ansible Galaxy roles
  hosts: kubernetes_hosts
  become: true
  # vars:
  #   kubeconfig_path: "/home/ucloud/.kube/config"
  # environment:
  #   KUBECONFIG: "{{ kubeconfig_path }}"

  tasks:
  
    
    
    - name: Initialize kube cluster
      ansible.builtin.shell:
        cmd: sudo kubeadm init --pod-network-cidr=10.244.0.0/16 --cri-socket=unix:///var/run/cri-dockerd.sock
