---
- name: Install Ansible Galaxy roles
  hosts: kubernetes_hosts
  connection: local
  tasks:
    - name: Include vars of vars.json
      ansible.builtin.include_vars:
        file: ../../.environmentals.json

    - name: Print NGROK_AUTHTOKEN
      ansible.builtin.debug:
        var: NGROK_AUTHTOKEN

    - name: Print NGROK_API_KEY
      ansible.builtin.debug:
        var: NGROK_API_KEY
    
    - name: Print ANSIBLE_USER
      ansible.builtin.debug:
        var: ANSIBLE_USER
    
    
    - name: Print ANSIBLE_HOST
      ansible.builtin.debug:
        var: ANSIBLE_HOST
      