---
- name: Install Ansible Galaxy roles
  become: true
  hosts: kubernetes_hosts
  vars:
    kubeconfig_path: "/home/ucloud/.kube/config"
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  roles:
    - geerlingguy.docker
    - gantsing.helm
    - gantsign.minikube
    - robertdebock.kubectl
    
  tasks:
    - name: Add user to docker group
      become: yes
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      tags: 
        - docker
      
    - name: Set Docker socket permissions
      become: yes
      file:
        path: /var/run/docker.sock
        mode: "0777"
      tags:
        - docker

    - name: Start minikube
      become: false
      command: minikube start --cpus=12 --memory=28000 --driver=docker

    - name: install pip3
      ansible.builtin.package:
        name: python3-pip
        state: present
  
    - name: install python3 libraries
      ansible.builtin.pip:
        name: "{{ item }}"
      loop:
        - kubernetes
        - openshift
        - docker
        - PyYAML

    - name: Create namespaces
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../../kubernetes-deployments/namespace-creation.yaml') | from_yaml_all }}"

    - name: Apply rabbitmq operator
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../../kubernetes-deployments/rabbitmq-operator.yaml') | from_yaml_all }}"

    - name: Apply rabbitmq definition
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../../kubernetes-deployments/rabbitmq-definition.yaml') | from_yaml_all }}"

    - name: Get minikube docker-env
      become: false
      shell: minikube docker-env
      register: minikube_docker_env

    - name: Copy base image Dockerfile to target machine
      copy:
        src: ../../base-image/Dockerfile
        dest: ./DockerfileBaseImage

    - name: Build backend base image
      community.docker.docker_image_build:
        path: "."
        name: "solveploy-backend-base-image"
        dockerfile: "DockerfileBaseImage"
        rebuild: "always"
        docker_host: "{{ (minikube_docker_env.stdout | regex_search('export DOCKER_HOST=\"(.*?)\"', '\\1')) | first }}"
        tls: "{{ (minikube_docker_env.stdout | regex_search('export DOCKER_TLS_VERIFY=\"(.*?)\"', '\\1')) | first | bool }}"
        validate_certs: "{{ (minikube_docker_env.stdout | regex_search('export DOCKER_TLS_VERIFY=\"(.*?)\"', '\\1')) | first | bool }}"
        ca_path: "{{ (minikube_docker_env.stdout | regex_search('export DOCKER_CERT_PATH=\"(.*?)\"', '\\1')) | first }}/ca.pem"
        client_cert: "{{ (minikube_docker_env.stdout | regex_search('export DOCKER_CERT_PATH=\"(.*?)\"', '\\1')) | first }}/cert.pem"
        client_key: "{{ (minikube_docker_env.stdout | regex_search('export DOCKER_CERT_PATH=\"(.*?)\"', '\\1')) | first }}/key.pem"

    - name: Copy services to target machine
      copy:
        src: ../../services
        dest: .

    - name: Build Docker images
      community.docker.docker_image_build:
        path: "{{ item.context }}"
        name: "{{ item.image }}"
        dockerfile: "{{ item.dockerfile }}"
        rebuild: "always"
        docker_host: "{{ (minikube_docker_env.stdout | regex_search('export DOCKER_HOST=\"(.*?)\"', '\\1')) | first }}"
        tls: "{{ (minikube_docker_env.stdout | regex_search('export DOCKER_TLS_VERIFY=\"(.*?)\"', '\\1')) | first | bool }}"
        validate_certs: "{{ (minikube_docker_env.stdout | regex_search('export DOCKER_TLS_VERIFY=\"(.*?)\"', '\\1')) | first | bool }}"
        ca_path: "{{ (minikube_docker_env.stdout | regex_search('export DOCKER_CERT_PATH=\"(.*?)\"', '\\1')) | first }}/ca.pem"
        client_cert: "{{ (minikube_docker_env.stdout | regex_search('export DOCKER_CERT_PATH=\"(.*?)\"', '\\1')) | first }}/cert.pem"
        client_key: "{{ (minikube_docker_env.stdout | regex_search('export DOCKER_CERT_PATH=\"(.*?)\"', '\\1')) | first }}/key.pem"
      async: 7200
      poll: 0
      register: docker_build
      loop:
        - {
            image: "frontend",
            dockerfile: "Dockerfile",
            context: "./services/frontend/",
          }
        - {
            image: "api-gateway",
            dockerfile: "Dockerfile",
            context: "./services/api_gateway/",
          }
        - {
            image: "job-handler",
            dockerfile: "Dockerfile",
            context: "./services/job_handler/",
          }
        - {
            image: "knowledge-base",
            dockerfile: "Dockerfile",
            context: "./services/knowledge_base/",
          }
        - {
            image: "mzn-pod",
            dockerfile: "Dockerfile",
            context: "./services/mzn_pod/",
          }
        - {
            image: "sat-pod",
            dockerfile: "Dockerfile",
            context: "./services/sat_pod/",
          }
        - {
            image: "maxsat-pod",
            dockerfile: "Dockerfile",
            context: "./services/maxsat_pod/",
          }

    - name: Wait for Docker image builds to finish
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 300
      loop: "{{ docker_build.results }}"

    - name: Get secret from rabbitmq-system namespace
      kubernetes.core.k8s_info:
        kind: Secret
        name: message-broker-default-user
        namespace: rabbitmq-system
      register: secret_info
      until: (secret_info.resources | default([])) | length > 0
      retries: 20
      delay: 10

    - name: Create secret in default namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: "{{ secret_info.resources[0].metadata.name }}"
            namespace: default
          type: "{{ secret_info.resources[0].type }}"
          data: "{{ secret_info.resources[0].data }}"

    - name: Apply Kubernetes deployments and services
      kubernetes.core.k8s:
        definition: "{{ item }}"
      loop:
        - "{{ lookup('file', '../../kubernetes-deployments/api-gateway-deployment.yaml') | from_yaml_all }}"
        - "{{ lookup('file', '../../kubernetes-deployments/api-gateway-service.yaml') | from_yaml_all }}"
        - "{{ lookup('file', '../../kubernetes-deployments/job-handler-deployment.yaml') | from_yaml_all }}"
        - "{{ lookup('file', '../../kubernetes-deployments/job-handler-service.yaml') | from_yaml_all }}"
        - "{{ lookup('file', '../../kubernetes-deployments/role-job-creator.yaml') | from_yaml_all }}"
        - "{{ lookup('file', '../../kubernetes-deployments/cluster-role-job-creator.yaml') | from_yaml_all }}"
        - "{{ lookup('file', '../../kubernetes-deployments/clusterrolebinding-job-creator.yaml') | from_yaml_all }}"
        - "{{ lookup('file', '../../kubernetes-deployments/knowledge-base-database-deployment.yaml') | from_yaml_all }}"
        - "{{ lookup('file', '../../kubernetes-deployments/knowledge-base-database-service.yaml') | from_yaml_all }}"
        - "{{ lookup('file', '../../kubernetes-deployments/knowledge-base-deployment.yaml') | from_yaml_all }}"
        - "{{ lookup('file', '../../kubernetes-deployments/knowledge-base-service.yaml') | from_yaml_all }}"
        - "{{ lookup('file', '../../kubernetes-deployments/frontend-deployment.yaml') | from_yaml_all }}"
        - "{{ lookup('file', '../../kubernetes-deployments/frontend-service.yaml') | from_yaml_all }}"
    
    - name: Add ngrok Helm repository
      ansible.builtin.command: helm repo add ngrok https://ngrok.github.io/kubernetes-ingress-controller

    - name: Update Helm repositories
      ansible.builtin.command: helm repo update

    - name: Install ngrok-ingress-controller
      kubernetes.core.helm:
        name: ngrok
        chart_ref: ngrok/kubernetes-ingress-controller
        release_namespace: ngrok-ingress-controller
        create_namespace: true
        values:
          credentials:
            apiKey: "{{ NGROK_API_KEY }}"
            authtoken: "{{ NGROK_AUTHTOKEN }}"
    
    - name: Apply Kubernetes deployments and services
      kubernetes.core.k8s:
        definition: "{{ item }}"
      loop:
        - "{{ lookup('file', '../../kubernetes-deployments/ngrok-ingress.yaml') | from_yaml_all }}"
