---
- hosts: localhost
  connection: local
  tasks:
    - name: Add ngrok Helm repository
      ansible.builtin.command: helm repo add ngrok https://ngrok.github.io/kubernetes-ingress-controller

    - name: Update Helm repositories
      ansible.builtin.command: helm repo update

    - name: Install ngrok-ingress-controller
      kubernetes.core.helm:
        name: ngrok
        chart_ref: ngrok/ngrok-ingress-controller
        release_namespace: ngrok-ingress-controller
        create_namespace: true
        values:
          credentials:
            apiKey: "{{ NGROK_API_KEY }}"
            authtoken: "{{ NGROK_AUTHTOKEN }}"
    
    - name: Apply Kubernetes deployments and services
      kubernetes.core.k8s:
        src: "{{ item }}"
      loop:
        - ../../kubernetes-deployments/ngrok-ingress.yaml
