---
- hosts: localhost
  connection: local
  tasks:
    - name: Install ngrok-ingress-controller
      kubernetes.core.helm:
        name: ngrok-ingress-controller
        chart_ref: ngrok/kubernetes-ingress-controller
        release_namespace: ngrok-ingress-controller
        chart_repo_url: https://ngrok.github.io/kubernetes-ingress-controller
        create_namespace: true
        values:
          credentials:
            apiKey: "{{ NGROK_API_KEY }}"
            authtoken: "{{ NGROK_AUTHTOKEN }}"
    
    - name: Apply Kubernetes deployments and services
      kubernetes.core.k8s:
        src: "{{ item }}"
      loop:
        - ../../kubernetes-deployments/ngrok-ingress.yaml
