apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-api-gateway
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      "app": "api-gateway"
  delay:
    latency: "100ms"
  duration: "30s"

apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-api-gateway
spec:
  action: pod-failure
  mode: all
  selector:
    namespaces:
      - default
    labelSelectors:
      "app": "api-gateway"
  scheduler: "@every 10m"
  duration: "30s"

apiVersion: chaos-mesh.org/v1alpha1
kind: IoChaos
metadata:
  name: io-chaos-frontend
spec:
  action: latency
  mode: all
  selector:
    namespaces:
      - default
    labelSelectors:
      "app": "frontend"
  scheduler: "@every 10m"
  duration: "30s"
  delay:
    latency: "100ms"
    duration: "60s"

apiVersion: chaos-mesh.org/v1alpha1
kind: KernelChaos
metadata:
  name: kernel-chaos-job-handler
spec:
  action: io
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      "app": "job-handler"
  scheduler: "@every 10m"
  duration: "30s"

apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: stress-chaos-knowledge-base
spec:
  action: stress
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      "app": "knowledge-base"
  scheduler: "@every 10m"
  duration: "30s"
  stressors:
    memory:
      containerName: knowledge-base
      size: "50%"
      workers: 1
    cpu:
      containerName: knowledge-base
      workers: 1
