apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: job-creator
rules:
  - apiGroups: ["batch"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "list"]
  - apiGroups: [""] 
    resources: ["nodes"]
    verbs: ["*"]
  - apiGroups: [""] 
    resources: ["namespaces"]
    verbs: ["*"]
  - apiGroups: ["apps"] 
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]