name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'services/job_handler/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'services/job_handler/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Registry
      run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin docker.io

    - name: Build the job-handler Docker image
      run: docker build services/job_handler/ --file services/job_handler/Dockerfile --tag docker.io/${{ secrets.DOCKER_USERNAME }}/job-handler:latest

    - name: Push the job-handler Docker image
      run: docker push docker.io/${{ secrets.DOCKER_USERNAME }}/job-handler:latest