name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'services/knowledge_base/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'services/knowledge_base/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Registry
      run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin docker.io

    - name: Build the knowledge-base Docker image
      run: docker build services/knowledge_base/ --file services/knowledge_base/Dockerfile --tag docker.io/${{ secrets.DOCKER_USERNAME }}/knowledge-base:latest

    - name: Push the knowledge-base Docker image
      run: docker push docker.io/${{ secrets.DOCKER_USERNAME }}/knowledge-base:latest