name: Maxsat pod CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'services/maxsat_pod/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'services/maxsat_pod/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Registry
      run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin docker.io

    - name: Build the maxsat-pod Docker image
      run: docker build services/maxsat_pod/ --file services/maxsat_pod/Dockerfile --tag docker.io/${{ secrets.DOCKER_USERNAME }}/maxsat-pod:latest

    - name: Push the maxsat-pod Docker image
      run: docker push docker.io/${{ secrets.DOCKER_USERNAME }}/maxsat-pod:latest